[package]
name = "swapi"
version = "0.1.0"
authors = ["Kyle Surowiec <kylesurowic@me.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0.80"
serde_json = "1.0.33"